### ISSUE TITLE
Add Form validation

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#90]
I have done for all the required fields these are left
The form needs to be validated on following points -
- Year should be a number
- url must be a proper url
- seasons must be a number
- episode_length must be a number
- season_length must be a number

**Comment by Pk13055** [comment]
Only these are left?

**Comment by gsc2001** [comment]
Ya

**Comment by gsc2001** [comment]
I dont find any more .

**Comment by Pk13055** [comment]
You have not rendered the error appropriately as well. You need to link the response received to the various fields in case the form is not sucessfully linked. Also, for all the fields something similar to [this[(https://vuetifyjs.com/en/components/textarea/#beautiful-forms) is required for validation, right? Maybe we can use [vuelidate](https://vuetifyjs.com/en/components/forms/#vuelidate) instead of the default validation. This will allow for the error injection as mentioned earlier

**Comment by gsc2001** [comment]
I left the error message to be changed by this issue only. But then i forgot to mention it here. Yeah sure we can use vuelidate.

**Comment by gsc2001** [comment]
So do i work on this or leave for somebody else to pick it up

**Comment by Pk13055** [comment]
Ideally since this is the crux of the application I would prefer you work on it, but if you don't want to, we can leave it to someone else, maybe @Megha-Bose

**Comment by gsc2001** [comment]
I will work on it

**Comment by gsc2001** [comment]
I am doing this with vuelidate. Ok?

**Comment by gsc2001** [comment]
Steps: -

- [ ] Common form 
- [ ] Specific form
